{
 "title": "OpenCensus HTTP/gRPC Metrics",
 "description": "Dashboard to view OpenCensus stats",
 "tags": [
  "prometheus",
  "opencensus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"opencensus\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "gRPC Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "$instance", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "instance" },
    {
     "title": "gRPC Server: Received Bytes Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_server_request_bytes_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Server: Sent Bytes Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_server_response_bytes_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Server: Server Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "repeat": "instance",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_server_server_elapsed_time_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Server: Error Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "repeat": "instance",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(grpc_io_server_error_count{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}} - {{canonical_status}}"
      }
     ]
    },
    {
     "title": "gRPC Server: Received Messages Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_server_request_count_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Server: Sent Messages Per Sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_server_response_count_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "$instance", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "instance" },
    {
     "title": "gRPC Client: Sent Bytes Per Sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_client_request_bytes_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client: Received Bytes Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_client_response_bytes_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client: Roundtrip Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "repeat": "instance",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_client_roundtrip_latency_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client: Error Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(grpc_io_client_error_count{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}} - {{canonical_status}}"
      }
     ]
    },
    {
     "title": "gRPC Client: Sent Messages Per Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "repeat": "instance",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_client_request_count_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "gRPC Client: Received Messages Per Sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_io_client_response_count_sum{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  }
 ]
}